name: Assignment
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: date
  windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        run: date
  macos:
    name: MacOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        run: date
  depends:
    name: Depends
    needs: [ubuntu, windows, macos]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: date