name: First workflow of Github Action learning journey
on: [push]
jobs:
  jobs1:
    name: First job of first group
    runs-on: ubuntu-latest
    steps:
      - name: First step of first job
        uses: actions/checkout@v2
      - name: Second step of first job
        run: env | sort
  jobs2:
    name: First job of second group
    runs-on: windows-latest
    steps:
      - name: First step of second job
        uses: actions/checkout@v2
      - name: Second step of second job
        run: env | sort

